CREATE TABLE task
(
    id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(255) NOT NULL,
    description varchar(255) NOT NULL,
    status      varchar(30)  NOT NULL,
    due_date    timestamp    NOT NULL
);